# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: q1xuanx
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: student-manage
service: student-manage

plugins: 
  - serverless-python-requirements

custom: 
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: true
    useStaticCache: false
    invalidateCaches: true

functions: 
  app: 
    handler: app/main.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}
      - httpApi:
          method: any
          path: /

provider: 
  name: aws
  architecture: x86_64
  runtime: python3.10
  timeout: 30
  region: ap-southeast-1
  logRetentionInDays: 14
  environment:
    USERNAME_DB: ${env:username_db}
    PASSWORD_DB: ${env:password_db}
    PORT_DB: ${env:port_db}
    NAME_DB: ${env:name_db}
    SERVER_DB: ${env:server_db}
    TOKEN_API: ${env:token_api}
    RAW_USERNAME: ${env:raw_username}
    RAW_PASSWORD: ${env:raw_password}